force-app/main/default/objects/Opportunity/fields/isTest__c.field-meta.xml
<CustomField>
    <fullName>isTest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isTest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Progress_Tracker_Object_Setting__mdt/Progress_Tracker_Object_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Progress Tracker Object Setting</label>
    <pluralLabel>Progress Tracker Object Settings</pluralLabel>
</CustomObject>

force-app/main/default/classes/ProgressTrackerControllerTest.cls
@isTest
public class ProgressTrackerControllerTest {

    /* Generic test right here, just grabs an object setting after inseting it
       in */
    @isTest static void getProgressTrackerObjectSettingsWithOpportunity() {
        Opportunity testOpportunity = new Opportunity(
            StageName = 'Sourcing Demand',
            CloseDate = date.valueOf('2016-01-01'),
            Name = 'Test Opportunity',
            IsTest__c = true
        );
        insert testOpportunity;

        Progress_Tracker_Object_Setting__mdt testObjectSetting = [SELECT Id, IsActive__c, Object_Name__c, Label
                                                                  FROM Progress_Tracker_Object_Setting__mdt
                                                                  WHERE Label =: 'Testing Setting'];

        Test.startTest();
        ProgressTrackerController.getProgressTrackerObjectSettings(testObjectSetting.Id, testOpportunity.Id);
        Test.stopTest();
    }
}